Fix compatibility issues.
NoMethodError: undefined method `dump_schemas' for
ActiveRecord::Base:Class was being thrown, since I was inadvertently
relying on functionality only present when used in conjunction with the
activerecord-postgres-dump-schemas gem (which backports Rails 5
functionality to Rails 4).